### ISSUE TITLE
Cant save nodes that "Allow vary by culture" in the content root

### ISSUE THREAD

**Issue by AvihayTWB** [ZioTino/Our.Umbraco.Skipper#1]
Hi. I tried to use skipper in a new Umb 9.2 installation with SQL DB.
After install via nuget when the Home DocType "Allow vary by culture" - you cant save it.
No log error shows, but this:
![console error](https://user-images.githubusercontent.com/98151337/150495416-4c26ca18-17e5-4291-a8a9-e0099e45fe63.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/98151337/150495531-c7acaaa6-5d86-4207-8b51-2dbe8577bcb6.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/98151337/150495478-1bc04340-88f3-4d72-b1c7-d714e4e73d00.jpg)

When I remove skipper from project - I can save the node again...

Any idea how to solve this?

**Comment by ZioTino** [comment]
Hi @AvihayTWB, thank you for submitting this bug. 
I've made some changes and released v1.0.1. Try updating Skipper and see if this fixes your problem!

**Comment by AvihayTWB** [comment]
Hi @ZioTino, thanks for the quick fix. 
It did solve the problem and Im able to save nodes when skipper is part of the solution now. 

I'll give it a try later in the project, hoping the url-encoding from hebrew will not be a problem as it was with v8 Virtual Nodes package...
Thanks again :)
